#### Inverted dropout regularization

In [1]:
import numpy as np

In [15]:
a3 = np.random.rand(4, 5)
print("Activation a3 =\n", a3)
print("----------------------------------------------------------")
keep_prob = 0.8
d3 = np.random.rand(a3.shape[0], a3.shape[1]) < keep_prob
a3 = a3 * d3
print("After applying dropout mask a3 =\n", a3)
print("----------------------------------------------------------")
a3 = a3 / keep_prob
print("After scaling a3 =\n", a3)

Activation a3 =
 [[0.90132192 0.70536025 0.46661512 0.86488024 0.18512086]
 [0.97889789 0.84632496 0.28584596 0.81876904 0.08209633]
 [0.03797562 0.71233343 0.62462302 0.5911225  0.44586081]
 [0.36771729 0.06168375 0.99082506 0.2786859  0.7742671 ]]
----------------------------------------------------------
After applying dropout mask a3 =
 [[0.90132192 0.70536025 0.46661512 0.86488024 0.18512086]
 [0.97889789 0.84632496 0.28584596 0.         0.        ]
 [0.03797562 0.71233343 0.62462302 0.         0.44586081]
 [0.         0.06168375 0.99082506 0.         0.7742671 ]]
----------------------------------------------------------
After scaling a3 =
 [[1.1266524  0.88170032 0.5832689  1.0811003  0.23140107]
 [1.22362236 1.0579062  0.35730745 0.         0.        ]
 [0.04746953 0.89041679 0.78077878 0.         0.55732602]
 [0.         0.07710468 1.23853133 0.         0.96783387]]
