In [1]:
import numpy as np

In [2]:
W = np.random.rand(3, 4)
print("Original array:")
print(W)

Original array:
[[0.90818819 0.12752864 0.39133134 0.05294429]
 [0.76780046 0.94117366 0.87787685 0.58526532]
 [0.08525593 0.099694   0.97730237 0.49707938]]


In [4]:
v = np.zeros_like(W)
print("\nArray of zeros with the same shape as W:")
print(v)


Array of zeros with the same shape as W:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
